---
- hosts: pi
  tasks:
    - name: install SSH key
      authorized_key: user=pi key="{{ lookup('file', '../data/master_key.pub') }}"

    - name: apt-get update
      sudo: yes
      apt: update_cache=yes cache_valid_time=86400

    - name: install basic requirements
      sudo: yes
      apt: name={{item}} state=latest
      with_items:
        - rsync
        - i2c-tools
        - python3
        - python3-pip
        - fluidsynth
        - fluid-soundfont-gm
        - libasound2-dev
        - libjack-jackd2-dev
        - busybox-syslogd

    - name: remove unnecessary packages
      sudo: yes
      apt: name={{item}} state=absent purge=yes autoremove=yes
      with_items:
        - pi-bluetooth
        - ntp
        - triggerhappy
        - dbus
        - dphys-swapfile
        - rsyslog

    - name: enable I2C module
      sudo: yes
      lineinfile: dest=/etc/modules line="i2c-dev" insertafter=EOF

    - name: enable I2C in boot.txt
      sudo: yes
      lineinfile: dest=/boot/config.txt line="dtparam=i2c_arm=on" insertafter=EOF

    - name: disable unnecessary services
      sudo: yes
      service: name={{item}} enabled=no
      with_items:
        - bootlogs
        - console-setup

    - name: mount /boot read-only
      sudo: yes
      replace: dest=/etc/fstab regexp='^(\/dev\/mmcblk0p1\s+\/boot\s+vfat\s+)defaults(\s+0\s+2)$' replace='\1defaults,ro\2' backup=yes

    - name: mount / read-only
      sudo: yes
      replace: dest=/etc/fstab regexp='^(\/dev\/mmcblk0p2\s+\/\s+ext4\s+)defaults,noatime(\s+0\s+1)$' replace='\1defaults,noatime,ro\2' backup=yes

    - name: copy project directory
      synchronize: src=../../heykel dest=/home/pi recursive=yes delete=yes
