---
- hosts: pi
  tasks:
    - name: install SSH key
      authorized_key: user=pi key="{{ lookup('file', '../data/master_key.pub') }}"

    - name: apt-get update
      become: yes
      apt: update_cache=yes cache_valid_time=86400

    - name: install basic requirements
      become: yes
      apt: name={{item}} state=latest
      with_items:
        - rsync
        - i2c-tools
        - python3
        - python3-pip
        - fluidsynth
        - fluid-soundfont-gm
        - libasound2-dev
        - libjack-jackd2-dev

    - name: remove unnecessary packages
      become: yes
      apt: name={{item}} state=absent purge=yes autoremove=yes
      with_items:
        - pi-bluetooth
        - ntp

    - name: enable I2C module
      become: yes
      lineinfile: dest=/etc/modules line="i2c-dev" insertafter=EOF

    - name: enable I2C in boot.txt
      become: yes
      lineinfile: dest=/boot/config.txt line="dtparam=i2c_arm=on" insertafter=EOF

    - name: install i2c-tools
      become: yes
      apt: name=i2c-tools state=latest

    - name: copy project directory
      synchronize: src=../../heykel dest=/home/pi recursive=yes delete=yes
